### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by leuc** [phoboslab/wipeout-rewrite#42]
Flatpak would be great for easy installation on Steam Deck.

Here is a working Manifest `org.phoboslab.wipeout.yml`

```yaml
---
app-id: org.phoboslab.wipeout
runtime: org.freedesktop.Platform
runtime-version: '21.08'
sdk: org.freedesktop.Sdk
command: /app/wipegame

cleanup:
  - /lib/pkgconfig
  - /lib/debug
  - '*.la'
  - '*.a'

modules:
  - shared-modules/glew/glew.json
  - shared-modules/glu/glu-9.json
  - name: wipeout-data
    buildsystem: simple
    build-commands:
      - unzip -n wipeout-data-v01.zip
    sources:
      - type: file
        url: https://phoboslab.org/files/wipeout-data-v01.zip
        sha1: 16f9f188d171d2b1f891766a1e4ac2df7e70973e
    post-install:
      - mv wipeout $FLATPAK_DEST/wipeout

  - name: wipeout-rewrite
    buildsystem: simple
    build-commands:
      - L_FLAGS="$(pkg-config --libs glew glu) -lm" make sdl
    sources:
      - type: git
        url: https://github.com/phoboslab/wipeout-rewrite.git
    post-install:
      - install -D -m 755 -t $FLATPAK_DEST wipegame

finish-args:
  - --device=dri
  - --share=ipc
  - --share=network
  - --socket=x11
  - --socket=pulseaudio
  - --filesystem=home
```

Needs Flathub git sub-module for shared-modules

```ini
[submodule "shared-modules"]
	path = shared-modules
	url = https://github.com/flathub/shared-modules.git
```

```sh
flatpak-builder --user --install inst-dir org.phoboslab.wipeout.yml
```

if flatpak-builder fails downloading glu with certificate errors, apply this patch in shared-modules
```patch
diff --git a/glu/glu-9.json b/glu/glu-9.json
index c054749..e0aba90 100644
--- a/glu/glu-9.json
+++ b/glu/glu-9.json
@@ -5,6 +5,9 @@
     {
       "type": "archive",
       "url": "https://archive.mesa3d.org/glu/glu-9.0.2.tar.xz",
+      "mirror-urls": [
+          "ftp://ftp.freedesktop.org/pub/mesa/glu/glu-9.0.2.tar.xz"
+      ],
       "sha256": "6e7280ff585c6a1d9dfcdf2fca489251634b3377bfc33c29e4002466a38d02d4"
     }
   ],
```
